### ISSUE TITLE
Not working on production

### ISSUE THREAD

**Issue by heidiv** [davydotcom/retina_tag#18]
Hello! I'm sure this is something on my end, not yours, but I was wondering if you had any insight as to why retina_tag would work beautifully on my local development environment, but not my production server? 

On the server, data-hidpi-src & data-lowdpi-src attributes are not being added to <img> tags. I checked my public/assets dir and the @2x versions are there. The retina_tag gem is installed. Other thoughts? Thanks in advance!

**Comment by RustComet** [comment]
I am also having this issue. I have used the gem before on other projects, but it seems to be broken on my latest. 

```
rails 4.2.5
ruby 2.3.0
```

**Comment by davydotcom** [comment]
Ill have to see what might have changed in latest rails to  cause this.

**Comment by naps62** [comment]
Here's the cause of the issue: https://github.com/rails/sprockets-rails/issues/237

In production, `Rails.application.assets` is only set if `config.assets.compile` is enabled (and it's not enabled by default in production)

You can get the same info using `Rails.application.assets_manifest`, although you have to basically implement the `find_asset` logic yourself

I'm trying to fix this myself right now, since I need to fix this for my current project
